-- Create chat_history table without foreign key to auth.users
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS chat_history (
    id bigint generated by default as identity primary key,
    user_id text not null, -- Changed from uuid references auth.users to text
    role text not null check (role in ('user', 'model', 'system')),
    content text not null,
    tool_calls jsonb, -- Stores tool usage metadata
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_chat_history_user_date ON chat_history (user_id, created_at DESC);
