-- Migration: Create user_equipment table for granular equipment tracking
CREATE TABLE IF NOT EXISTS public.user_equipment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    equipment_name text NOT NULL,
    category text NOT NULL,
    created_at timestamptz DEFAULT now(),
    UNIQUE(user_id, equipment_name)
);

-- Enable RLS
ALTER TABLE public.user_equipment ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only access their own equipment
CREATE POLICY "Users can view own equipment" ON public.user_equipment
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own equipment" ON public.user_equipment
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own equipment" ON public.user_equipment
    FOR DELETE USING (auth.uid() = user_id);

-- Index for fast lookup
CREATE INDEX IF NOT EXISTS idx_user_equipment_user_id ON public.user_equipment(user_id);
